export {default as Menu } from './menu/menu'
export {default as Home } from './home/home'
export {default as Portfolio } from './portfolio/portfolio'
export {default as Skills } from './skills/skills'
export {default as Footer } from './footer/footer'
export {default as Contact } from './contact/contact'